"""
Create a second-order markov chain that can generate words.
@author Rookie
"""

"""
Things to do:

    - How is a markov list generated?

    - Outline functions, top-down

    - Verify that there are no missing invokes

    - Create tests + Program functions, down-top

    - Polish README.md, the bullet points for notes look weird

    - Add explanations and methodology to README.md
"""

def write_network(markov_list):
    """
    Takes a stored `markov_list` and overwrites it to "markov_data.txt"
    """
    ...

def read_network():
    """
    Reads "markov_data.txt" and returns a stored markov chain.
    """

    # SETUP
    # The markov chain to return
    # The current token map to store into a markov[#]

    # CODE
    # Open the file through a `with as`
    # Use next() a few times, probably
    # Run a for loop on the file
    # Store the second line as markov[0] = probability list
    # After the third line, the real stuff begins
    # Reading a line
        # If there's a #
            # add the current token map to markov IF the current token map isn't empty
            # clear the current token map
        # Otherwise
            # read the line
            # if the len(split) = 1?
                # add a key
            # otherwise
                # split and add a probability list

    ...

def make_markov_network():
    """
    Returns a [markov chain] after reading a hardcoded text file.
    """
    ...

def find_probability_list(markov_list, order, token):
    """
    Chooses a token map from `markov_list` based on the `order`th order of tokens.

    Uses `token` as the key.
    """

    # Start analyzing markov_list[order]

    while False: # for loop with index and skip 2
        # Does `index` have the `token`?
        # If so, return the probability list at `index + 1`
        ...
    # Throw up

def choose_random_token(probability_list):
    """
    Chooses a random token from `probability_list`.
    """

    # Generate a random number of set [0.0, 1.0)
    # Generate a "right boundary" count
        # It will be 1.0 at the end of the loop

    while False: # should instead be a for loop with an index, as well as skip 2
        # Add the element of `index + 1` (the probability) to the right boundary
        # If the earlier-set random number is NOW less than the right boundary, return element of `index`
        ...

def use_markov_network(markov_list):
    """
    Returns a String generated by a [markov chain] `markov_list`.
    """

    # SETUP
    # Var: The string to return
    # Var: Context variable to select tokens

    # CODE
    # Invoke `choose_random_token` for markov_list[0], then get the token
    # If "END" has been pulled, return ""
    # Set the context to the first character
    # Choose a probability list from markov_list[1]
    # Invoke `choose_random_token` for the probability list, then get the token
    # If "END", return "#"
    # Set the context to the first and second character
    
    while False: # Loop for the second order Markov Chain
        # Choose a probability list from markov_list[2]
        # Invoke `choose_random_token` for the probability list, then get the token
        # If "END", return string
        # Set the context to the second character of the old one, and the new character combined
        ...

def main():
    """
    Prompts the user to type "make" to make the markov chain or "use" to run the markov chain.
    """
    # Set a blank string variable for the input
    # Get a loop that is broken once the string variable is empty
    while False:
        # Prompt the user to type "make" or "use"
        # If neither is used, repeat
        ...
    # If make, invoke `write_network` and `make_markov_network`
    # If use, invoke `read_network`, `use_markov_network`, and `print`
    ...

if (__name__ == "__main__"):
    main()