"""
Using Python to create a second-order markov chain that can generate words.
@author Rookie
"""

def write_network(markov_list):
    """
    Takes a stored `markov_list` and overwrites it to "markov_data.txt"
    """
    ...

def read_network():
    """
    Reads "markov_data.txt" and returns a stored markov chain.
    """
    ...

def make_markov_network():
    """
    Retruns a [markov chain] after reading a hardcoded text file.
    """
    ...

def find_probability_list(markov_list, order):
    """
    Chooses a token map from `markov_list` based on the `order`th order of tokens.
    """
    ...

def choose_random_token(probability_list):
    """
    Chooses a random token from `probability_list`.
    """
    ...

def use_markov_network(markov_list):
    """
    Returns a String generated by a [markov chain] `markov_list`.
    """

    # SETUP
    # Var: The string to return
    # Var: Context variable to select tokens

    # CODE
    # Invoke `choose_random_token` for markov_list[0], then get the token
    # If "END" has been pulled, return ""
    # Set the context to the first character
    # Choose a probability list from markov_list[1]
    # Invoke `choose_random_token` for the probability list, then get the token
    # If "END", return "#"
    # Set the context to the first and second character
    
    while False: # Loop for the second order Markov Chain
        # Choose a probability list from markov_list[2]
        # Invoke `choose_random_token` for the probability list, then get the token
        # If "END", return string
        # Set the context to the second character of the old one, and the new character combined
        ...

def main():
    """
    Prompts the user to type "make" to make the markov chain or "use" to run the markov chain.
    """
    # Set a blank string variable for the input
    # Get a loop that is broken once the string variable is empty
    while False:
        # Prompt the user to type "make" or "use"
        # If neither is used, repeat
        ...
    # If make, invoke `write_network` and `make_markov_network`
    # If use, invoke `read_network`, `use_markov_network`, and `print`
    ...

if (__name__ == "__main__"):
    main()