"""
Create a second-order markov chain that can generate words.
@author Rookie
"""

"""
Things to do:

    - How is a markov list generated?

    - Outline functions, top-down

    - Assertions for debugging

    - Verify that there are no missing invokes

    - Create tests + Program functions, down-top

    - Polish README.md, the bullet points for notes look weird

    - Add explanations and methodology to README.md
"""

def make_markov_network():
    """
    Returns a [markov chain] after reading a hardcoded text file.
    """
    ...

def write_probability_list(probability_list):
    """
    Takes a stored `probability_list` and returns a string representation of it.
    """
    # Initialize the representative string.

    while False: # For loop
        # Use str() to add a " " to the string.
        # If it's not the end of the string, add " ".
        ...
    
    # Return the string.

def write_network(markov_list):
    """
    Takes a stored `markov_list` and overwrites it to "markov_data.txt"
    """

    # initialize a string to be stored into a file.

    while False: # for each order in the markov chain:
        # Write the double hashtag header
        # Write each element of each token map on a separate line, partly through `write_probability_list`
        ...
    ...

def read_network_file_each_line(markov_list, line):
    # CODE
    # If there's a #
        # Append a new token map to the markov chain
    # Otherwise
        # If the len(split) == 1
            # Add the line to the most recent token map
        # Else
            # Split the line into a probability list and add it to the most recent token map
    # Return the markov_list, just in case
    # A refactoring may need to remove the above line
    ...

def read_network_file():
    """
    Reads "markov_data.txt" and returns a stored markov chain.
    """

    # SETUP
    # The markov chain to return
    # The current token map to store into a markov[#]

    # DODE
    # Open the file through a `with as`
        # Run a for loop on the file
            # Strip the line for cleanliness
            # Invoke `markov_chain = read_network_file_each_line` to prevent overnesting
    # Return markov list
    ...

def find_probability_list(markov_list, order, token):
    """
    Chooses a token map from `markov_list` based on the `order`th order of tokens.

    Uses `token` as the key.
    """

    # Start analyzing markov_list[order]

    while False: # for loop with index and skip 2
        # Does `index` have the `token`?
        # If so, return the probability list at `index + 1`
        ...
    # Throw up

def choose_random_token(probability_list):
    """
    Chooses a random token from `probability_list`.
    """

    # Generate a random number of set [0.0, 1.0)
    # Generate a "right boundary" count
        # It will be 1.0 at the end of the loop

    while False: # should instead be a for loop with an index, as well as skip 2
        # Add the element of `index + 1` (the probability) to the right boundary
        # If the earlier-set random number is NOW less than the right boundary, return element of `index`
        ...

def use_markov_network(markov_list):
    """
    Returns a String generated by a [markov chain] `markov_list`.
    """

    # SETUP
    # Var: The string to return
    # Var: Context variable to select tokens

    # CODE
    # Choose a probability list from markov_list[0] using `find_probability_list`
    # Invoke `choose_random_token` for the probability list, then get the token
    # If "END" has been pulled, return ""
    # Set the context to the first character
    # Choose a probability list from markov_list[1]
    # Invoke `choose_random_token` for the probability list, then get the token
    # If "END", return "#"
    # Set the context to the first and second character
    
    while False: # Loop for the second order Markov Chain
        # Choose a probability list from markov_list[2]
        # Invoke `choose_random_token` for the probability list, then get the token
        # If "END", return string
        # Set the context to the second character of the old one, and the new character combined
        ...

def main():
    """
    Prompts the user to type "make" to make the markov chain or "use" to run the markov chain.
    """
    # Set a blank string variable for the input
    # Get a loop that is broken once the string variable is empty
    while False:
        # Prompt the user to type "make" or "use"
        # If neither is used, repeat
        ...
    # If make, invoke `write_network` and `make_markov_network`
    # If use, invoke `read_network_file`, `use_markov_network`, and `print`
    ...

if (__name__ == "__main__"):
    main()